Add data_set_id to Functions.create
cognitedata/cognite-sdk-python-experimental pull request #106
Opened 2020-10-13 09:10 UTC by haakonvt

Let me know if this is okey, it would make it much easier to work with for e.g. AIR 😄  @senickel

2020-10-13 10:10 UTC, pavelzubarev commented on cognite/experimental/_api/functions.py
> +        data_set_id: Optional[int] = None,
The big question for me should we ever expose internal IDs vs. external IDs. I believe external IDs are the way to go and we should not require client code to resolve that explicitly. What do you think, @haakonvt

2020-10-13 10:12 UTC, haakonvt commented on cognite/experimental/_api/functions.py
> +        data_set_id: Optional[int] = None,
Boy if I agree ;) But have a look at the FilesAPI.upload; it only accepts `data_set_id` 😢

2020-10-13 12:12 UTC, senickel commented on cognite/experimental/_api/functions.py
> +        data_set_id: Optional[int] = None,
or do both?

2020-10-14 14:12 UTC, HMEiding requested changes
I think adding the argument `data_set_id` to `FunctionsAPI.create()` is a bit misleading since it suggests that the `data_set_id` is referring to the _**function**_ and not the file. I would much rather have for example a helper function `FunctionsAPI.upload_file_from_folder()` which could have `data_set_id` as an optional argument and return a `file_id`.

2020-10-14 14:14 UTC, haakonvt commented
> I think adding the argument `data_set_id` to `FunctionsAPI.create()` is a bit misleading since it suggests that the `data_set_id` is referring to the _**function**_ and not the file. I would much rather have for example a helper function `FunctionsAPI.upload_file_from_folder()` which could have `data_set_id` as an optional argument and return a `file_id`.

I agree and I like it! I'll see what I can make 🚀

2020-10-14 14:16 UTC, haakonvt commented
I'll abandon this one, since branch name is `add-data-set-id-to-functions-create`

2020-10-14 14:16 UTC, closed without merging