Function schedule data endpoint
cognitedata/cognite-sdk-python-experimental pull request #118
Opened 2020-12-02 12:48 UTC by qTipTip

# Some questions:

1. Should the SDK return `{'id' : 123, 'data' : {'key' : value}}`, or just
   `{'key' : value}`. I implemented the latter.
2. The mocking we use, what is that's main purpose? To avoid calling the API directly, we intercept the GET-request, and return a pre-configured JSON? Is this to only make
sure our SDK correctly calls the underlying API? 

# Commit messages

- Added a `get_data` method to the FunctionScheduleAPI.
- Added a `schedule_get_data_response` mock. What is the purpose of this? It intercepts the requests to the configured URL, and gathers statistics on the number of times called, etc?

2020-12-02 15:32 UTC, HMEiding requested changes
Nice! A couple of comments:
- It would be nice to also implement a method `get_data()` on the `FunctionSchedule` class. We've done the same for `get_response()` on the `FunctionCall` class.
- Update the CHANGELOG.md
- Bump the version.

2020-12-02 15:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        Get the data associated with a specific schedule.
```suggestion
        Get the input data associated with a specific schedule.
```

2020-12-02 15:36 UTC, HMEiding commented
> # Some questions:
> 1. Should the SDK return `{'id' : 123, 'data' : {'key' : value}}`, or just
>    `{'key' : value}`. I implemented the latter.
> 2. The mocking we use, what is that's main purpose? To avoid calling the API directly, we intercept the GET-request, and return a pre-configured JSON? Is this to only make
>    sure our SDK correctly calls the underlying API?
> 
> # Commit messages
> * Added a `get_data` method to the FunctionScheduleAPI.
> * Added a `schedule_get_data_response` mock. What is the purpose of this? It intercepts the requests to the configured URL, and gathers statistics on the number of times called, etc?

My take on your questions:

1. I think your solution is fine. This is in line with how we've done it for the `/response` endpoint.
2. Yes, with mocking we can test our code without calling the API directly. However, this means we will need to update the mocks whenever breaking changes occur in the API. Ideally, we should have integration tests as well, but we have so far not prioritized this.

2020-12-04 10:56 UTC, HMEiding commented on pyproject.toml
> +version = "0.31.2"
Looking at this:
https://semver.org/
I think we should bump the minor version? So I was probably wrong in bumping the patch version last time...

2020-12-04 11:33 UTC, qTipTip commented on pyproject.toml
> +version = "0.31.2"
Bumped to `0.32.0` instead :)

2020-12-04 14:13 UTC, HMEiding requested changes
Som updates needed.

2020-12-04 14:13 UTC, HMEiding commented on CHANGELOG.md
> +- Method `get_data` on the `FunctionSchedule`-class.
Update these two.

2020-12-04 14:13 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +    def get_data(self) -> dict:
Should this also be `get_input_data()`?

2020-12-04 14:13 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +        Get the input data associated to this schedule.
Update similarly to the API docs?

2020-12-04 14:13 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +            Input data associated with this schedule.
And here.

2020-12-04 14:13 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        Get the input data associated with a specific schedule.
Update similarly to the API docs?

2020-12-04 15:00 UTC, qTipTip commented on cognite/experimental/data_classes/functions.py
> +    def get_data(self) -> dict:
Done!

2020-12-04 15:02 UTC, qTipTip commented on cognite/experimental/data_classes/functions.py
> +            Input data associated with this schedule.
Done

2020-12-04 15:02 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +        Get the input data associated with a specific schedule.
Done!

2020-12-04 15:27 UTC, matzhaugen approved these changes
Small nit but otherwise lgtm

2020-12-04 15:27 UTC, matzhaugen commented on CHANGELOG.md
> +- Method `get_input_data` on the `FunctionScheduleAPI`-class.
Are both lines needed?

2020-12-04 15:30 UTC, HMEiding approved these changes
LGTM 💯

2020-12-04 15:48 UTC, merged