[MLOPS-602] Add function schedule retrieve method
cognitedata/cognite-sdk-python-experimental pull request #121
Opened 2020-12-07 09:32 UTC by matzhaugen

API: https://github.com/cognitedata/context-api/pull/1245

Docs: https://github.com/cognitedata/service-contracts/pull/1159/

2020-12-07 09:49 UTC, HMEiding requested changes
Nice stuff! Remember also:
- Add tests.
- CHANGELOG.md
- Bump minor version.

2020-12-07 09:49 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            Optional[FunctionSchedule]: Requested function schedule or None if it does not exist.
Are you sure `Optional` is correct? I suspect we rather get an exception. We should test this.

We have `Optional` for retrieve function, but I suspect that is because there we use the `/byids` endpoint, and the `CogniteClient` handles this gracefully by looking at `missing` in the error response. That being said. Should we perhaps implement a `/byids` for schedules as well, and then rather let the SDK use that endpoint? What do you think?

2020-12-07 09:49 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        """`Retrieve a single function schedule by id. <https://docs.cognite.com/api/playground/#operation/get-api-playground-projects-project-function-scheudles-by-id>`_
See my comment in your accompanying service-contracts PR.

2020-12-07 11:04 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +            Optional[FunctionSchedule]: Requested function schedule or None if it does not exist.
Let's remove optional for now and change it later if it becomes relevant

2020-12-07 11:06 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +        """`Retrieve a single function schedule by id. <https://docs.cognite.com/api/playground/#operation/get-api-playground-projects-project-function-scheudles-by-id>`_
k I've updated this

2020-12-07 13:18 UTC, HMEiding requested changes
Must also bump the version in pyproject.toml. And also update the PR description.

2020-12-07 13:18 UTC, HMEiding commented on CHANGELOG.md
> +- Method `retrieve` from `FunctionScheduleAPI`-class.
```suggestion
- Method `retrieve` to `FunctionScheduleAPI`-class.
```

2020-12-07 13:18 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            FunctionSchedule: Requested function schedule or None if it does not exist.
Did you test this?

2020-12-07 13:18 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +    rsps.assert_all_requests_are_fired = False
This is not needed.

2020-12-07 13:18 UTC, HMEiding commented on CHANGELOG.md
> +## [0.33.1] - 2020-12-08
I think we should bump the minor version, ref:
https://semver.org/

2020-12-07 13:43 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +            FunctionSchedule: Requested function schedule or None if it does not exist.
Against the API?

2020-12-07 13:45 UTC, matzhaugen commented on CHANGELOG.md
> +## [0.33.1] - 2020-12-08
:1

2020-12-07 13:45 UTC, matzhaugen commented on tests/tests_unit/test_api/test_functions.py
> +    rsps.assert_all_requests_are_fired = False
Removed

2020-12-07 13:45 UTC, matzhaugen commented on CHANGELOG.md
> +- Method `retrieve` from `FunctionScheduleAPI`-class.
fixed

2021-01-05 10:46 UTC, HMEiding requested changes
LGTM, just a couple of docs updates needed after the transition to `/byids`.

2021-01-05 10:46 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        """`Retrieve a single function schedule by id. <https://docs.cognite.com/api/playground/#operation/getFunctionSchedule>`_
This should now reference the `/byids` endpoint, which I notice is missing from the docs.

2021-01-05 10:46 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +    def retrieve(self, id: int) -> FunctionSchedule:
Should now be `Optional[FunctionSchedule]`.

2021-01-05 10:46 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            FunctionSchedule: Requested function schedule.
Should now be `Optional[FunctionSchedule]`

2021-01-05 11:09 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +    def retrieve(self, id: int) -> FunctionSchedule:
Fixed

2021-01-05 11:09 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +            FunctionSchedule: Requested function schedule.
Fixed

2021-01-05 12:35 UTC, HMEiding approved these changes
LGTM 💯

2021-01-05 12:38 UTC, merged