[CDF-10142] Add integrations and runs APIs
cognitedata/cognite-sdk-python-experimental pull request #123
Opened 2020-12-07 13:19 UTC by AlexThunder

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +Create a client and try next possible operations
Just leave it at "Create a client" as in `CONTEXTUALIZATION.md`. Add a note explaining that the API key must have read/write permissions for the "generic" ACL.

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +client = CogniteClient(api_key="<<itera-int-green api key>>", project="itera-int-green", base_url = "https://greenfield.cognitedata.com")
Shouldn't refer to itera-int-green, just "<<your-api-key>>" and "your-project". Remove base_url.

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +# Create integration
This should be done outside of the python code block to get nice headers as in https://raw.githubusercontent.com/cognitedata/cognite-sdk-python-experimental/master/CONTEXTUALIZATION.md

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#Get list
"List integrations"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +# Create integration
"Create an integration"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#Update existed integration
"Update an integration that already exists"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#getById
"Retrieve an integration by id"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#list of runs
"List integration runs"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#add new run with status
"Add a new run with status" or "Create a new integration run with status"

2020-12-07 13:41 UTC, wjoel commented on INTEGRATIONS&RUNS.MD
> +#delete integration with all runs
"Delete an integration and all its runs"

2020-12-07 13:41 UTC, wjoel commented on cognite/experimental/_api/integrationruns.py
> +        return IntegrationRunList([])
Should this return the full list? I don't understand this one.

2020-12-07 13:41 UTC, wjoel commented on tests/tests_unit/test_api/test_integrations.py
> +                    "step": 22,
Hm, I guess we allow this in the Python SDK even though metadata is a string->string map? Python SDK converts the value to string for the user?

But, for a mock, shouldn't it be string->string as that's what we return from the API?

2020-12-07 14:23 UTC, AlexThunder commented on cognite/experimental/_api/integrationruns.py
> +        return IntegrationRunList([])
Yes, it should be full list here.
Response is a list of objects with fields:
           external_id: str = None,
            statuses: List[Dict[str, Any]] = None

Where statuses contains list of Runs. So runs() method - returns those list adding externalId inside each of element.

2020-12-07 14:38 UTC, AlexThunder commented on tests/tests_unit/test_api/test_integrations.py
> +                    "step": 22,
As we store metadata to JSONB, I have set metadata in python as metadata: Dict[str, Any].
So now if we have integration response part : 
`    "metadata": {
        "aaa": "bbb",
        "ccc": 111
    }`
it is converted to dict in python 
`{'aaa': 'bbb', 'ccc': 111}`

And if we create new integration with this dict. It will be stored to database as JSON : 
`  "metadata": {
        "aaa": "bbb",
        "ccc": 111
    }`

2020-12-08 07:57 UTC, wjoel commented on tests/tests_unit/test_api/test_integrations.py
> +                    "step": 22,
That's a bug that we need to fix then, metadata should not allow arbitrary values, but only strings. In addition we have some restrictions on how large the metadata can be that we should also enforce at some point (as soon as possible). Here's the documentation from assets, for example:
`Custom, application specific metadata. String key -> String value. Limits: Maximum length of key is 128 bytes, value 10240 bytes, up to 256 key-value pairs, of total size at most 10240.`

2020-12-08 07:58 UTC, wjoel commented on cognite/experimental/_client.py
> +        self.runs = IntegrationsRunsAPI(self._config, api_version="playground", cognite_client=self)
This should be `integration_runs`

2020-12-08 08:43 UTC, AlexThunder commented on cognite/experimental/_client.py
> +        self.runs = IntegrationsRunsAPI(self._config, api_version="playground", cognite_client=self)
Done

2020-12-08 09:29 UTC, AlexThunder commented on tests/tests_unit/test_api/test_integrations.py
> +                    "step": 22,
Fixed

2020-12-14 09:58 UTC, mathialo requested changes
Please bump the (minor) [version number](https://github.com/cognitedata/cognite-sdk-python-experimental/blob/fbabbd0f2a77636cc229bf0066a3cfa757cbf1d8/pyproject.toml#L3), so that a new release is triggered. 

Other than that it seems good to me, great work!

2020-12-14 11:28 UTC, mathialo approved these changes

2020-12-14 13:48 UTC, merged