[MLOPS-626] Adding `limits`-argument to `list` methods.
cognitedata/cognite-sdk-python-experimental pull request #129
Opened 2021-01-06 13:31 UTC by qTipTip

This PR introduces the possibility of specifying a `limit` in the `list`-methods of `FunctionsAPI`, `FunctionsCallAPI`, and `FunctionsScheduleAPI`. If not specified, the `limit`-default is controlled by `LIST_LIMIT_DEFAULT` and is set to 25.

2021-01-06 15:19 UTC, qTipTip commented
Is a default limit of 25 sensible? It's what Assets has.

2021-01-12 14:32 UTC, HMEiding requested changes
Great! Just a few small comments.

2021-01-12 14:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of functions to list. Pass in -1, 'inf' or None to list all functions.
Should we be consistent and say `float("inf")` like elsewhere?

2021-01-12 14:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            limit = None
We agreed that this should be all elements, right? Passing `None` will result in the default limit in the API.

2021-01-12 14:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of function calls to list. Pass in -1, 'inf' or None to list all Function Calls.
The `self._list()` method requires `float("inf")` here:
https://github.com/cognitedata/cognite-sdk-python/blob/52645b05b00c81374a29cec412790067ae3af1a8/cognite/client/_api_client.py#L403

2021-01-12 14:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of schedules to list. Pass in -1, 'inf' or None to list all schedules.
Should we be consistent and say `float("inf")` like elsewhere?

2021-01-12 14:32 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            limit = None
We agreed that this should be all elements, right? Passing `None` will result in the default limit in the API.

2021-01-12 14:32 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +def mock_function_calls_list_response_with_limit(rsps):
Nitpick, but the `/list` endpoint is typically referred to as the "filter"-endpoint:
https://docs.cognite.com/api/v1/#operation/listAssets

I don't think we've been consistent with this, but we can try. 😆

2021-01-12 14:32 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +    response_body = {"items": [CALL_COMPLETED, CALL_SCHEDULED]}
FYI: The response body also returns a cursor, although I guess the tests don't operate on it. I like it to be as realistic as possible, but maybe we could skip it here. What do you think? Have you checked assets?

2021-01-12 14:32 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +    query_parameters = f"?limit={limit}"
We don't have query parameters to this endpoint.

2021-01-12 14:45 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of functions to list. Pass in -1, 'inf' or None to list all functions.
Done

2021-01-12 15:01 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            limit = None
Done

2021-01-12 15:02 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of function calls to list. Pass in -1, 'inf' or None to list all Function Calls.
Done

2021-01-12 15:02 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            limit (int, optional): Maximum number of schedules to list. Pass in -1, 'inf' or None to list all schedules.
Done

2021-01-12 15:02 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            limit = None
Done

2021-01-12 15:03 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +def mock_function_calls_list_response_with_limit(rsps):
Haha, ok :) Might as well try!

2021-01-12 15:12 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +    query_parameters = f"?limit={limit}"
True! Was left from initial testing.

2021-01-12 15:13 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +def mock_function_calls_list_response_with_limit(rsps):
Should I refactor the above one as well then? mock_function_calls_list_response

2021-01-12 15:20 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +    response_body = {"items": [CALL_COMPLETED, CALL_SCHEDULED]}
Assets have no reference to cursors in their tests. 

Not sure how crucial it is to mock this here.

2021-01-12 15:35 UTC, HMEiding approved these changes
LGTM 💯

2021-01-13 08:38 UTC, matzhaugen requested changes

2021-01-13 08:38 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +        if limit in [float("inf"), -1, None]:
The type of limit is `Optional[int]`, do you need to check `float('"inf")`?

2021-01-13 08:38 UTC, matzhaugen commented on cognite/experimental/_api/functions.py
> +        if limit in [float("inf"), -1, None]:
Same as above

2021-01-13 08:38 UTC, matzhaugen commented
Small comment, otherwise good.

2021-01-13 11:56 UTC, matzhaugen approved these changes

2021-01-13 11:57 UTC, merged