Fancy output for pipelines and pnid detect
cognitedata/cognite-sdk-python-experimental pull request #134
Opened 2021-01-15 13:33 UTC by sanderland

2021-01-18 12:36 UTC, chingyulin commented on cognite/experimental/data_classes/utils/rules_output.py
> +        "<table><tr>"  # Look mum I'm a frontend designer
fancy

2021-01-18 12:53 UTC, chingyulin commented on cognite/experimental/data_classes/utils/image.py
> +            f"Module {e.name} missing, 'pip install PIL numpy bounding_box pdf2image' for advanced visualization of results"
```suggestion
            f"Module {e.name} missing, 'pip install Pillow numpy bounding_box pdf2image' for advanced visualization of results"
```

2021-01-18 13:25 UTC, chingyulin commented on cognite/experimental/data_classes/utils/image.py
> +def draw_boxes(file_bytes, items):
We have `convert` endpoint, I think use it with `display(SVG(svg))` from `Ipython` could be an option?

2021-01-18 13:35 UTC, chingyulin commented on cognite/experimental/data_classes/contextualization.py
> +            return df._repr_html_()
return outside try-except?

2021-01-18 13:37 UTC, chingyulin requested changes
Some not so fancy suggestions

2021-01-18 13:48 UTC, sanderland commented on cognite/experimental/data_classes/utils/image.py
> +def draw_boxes(file_bytes, items):
i'm not sure I understand.

2021-01-18 14:43 UTC, chingyulin commented on cognite/experimental/data_classes/contextualization.py
> +        except:
```suggestion
        except ImportError:
```

2021-01-19 09:08 UTC, rebwib commented on cognite/experimental/data_classes/contextualization.py
> +class EntityMatchingMatchRule(CogniteResource):
Should this also be part of this PR, can not see it in the changelog.

2021-01-19 09:16 UTC, sanderland commented on cognite/experimental/data_classes/contextualization.py
> +class EntityMatchingMatchRule(CogniteResource):
- More specific job types returned from these endpoints, with helper methods that make processing and visualizing output easier.

2021-01-19 09:30 UTC, rebwib commented on cognite/experimental/_api/pnid_parsing.py
> +        """Retrieve the cached raw OCR result. Only works when detect has already been run.
Or if you run the vision endpoint, but we can add that when it has been added to the sdk.

2021-01-19 10:11 UTC, rebwib approved these changes
Very nice, looks like you have some black issues.

2021-01-19 12:29 UTC, chingyulin approved these changes
LGTM

2021-01-19 12:53 UTC, merged