Add templates, and remove relationships (playground)
cognitedata/cognite-sdk-python-experimental pull request #140
Opened 2021-02-02 10:20 UTC by andreavs

2021-02-02 16:45 UTC, sanderland commented on CHANGELOG.md
> +- Alpha CogniteClient.
no

2021-02-02 16:45 UTC, sanderland commented on cognite/experimental/data_classes/templates.py
> +    GraphQL SDL is used as the language to describe the structure of the templates and data types.
The GraphQL schema definition language

2021-02-02 16:47 UTC, sanderland commented on cognite/experimental/data_classes/templates.py
> +        self.time_series_id = time_series_id
.id ?

2021-02-02 16:50 UTC, sanderland requested changes
pizza time, will have another look tomorrow.

2021-02-02 20:41 UTC, Tapped commented on cognite/experimental/data_classes/templates.py
> +class TimeSeriesResolver(CogniteResource):
Actually the TimeSeriesResolver is deprecated. Instead the `ConstantResolver` or `RawResolver` should be used to retrieve the externalId of the TimeSeries.

2021-02-03 08:49 UTC, sanderland commented on cognite/experimental/data_classes/templates.py
> +class TimeSeriesResolver(CogniteResource):
NB this breaks the template completion in a way that's not clear how to resolve.

2021-02-03 09:09 UTC, sanderland commented on cognite/experimental/_api/templates.py
> +        self.query = TemplatesQuery(*args, **kwargs)
can this be simpler? e.g. i see no reason for .query to be in a sub-api.

2021-02-03 09:11 UTC, sanderland commented on cognite/experimental/_api/templates.py
> +        self.query = TemplatesQuery(*args, **kwargs)
my intuition is to have instances+query live in the top level, but you may understand templated better

2021-02-03 09:13 UTC, sanderland requested changes
some more comments.
+ docs in cognite.rst please

2021-02-03 09:15 UTC, Tapped commented on cognite/experimental/data_classes/templates.py
> +class TimeSeriesResolver(CogniteResource):
Yes, but we'll have to provide you an API for doing it. In the meanwhile assuming that a TimeSeries type is a ConstantResolver will work.

2021-02-03 09:32 UTC, andreavs commented on cognite/experimental/_api/templates.py
> +        self.query = TemplatesQuery(*args, **kwargs)
Tried to roughly follow how the 3d sdk is designed, which also deals with wanting to flatten a structure that is heavily nested in the api. In that case, e.g. the asset mappings are in their own sub-api, even though the path in the api is under the model revisions. That being said, i do not have strong feelings on it, so we can move it

2021-02-04 08:24 UTC, sanderland commented on cognite/experimental/data_classes/templates.py
> +    def _load(cls, resource: Union[Dict, str], cognite_client=None):
can this be .super() into fixing fieldresolvers?

2021-02-04 08:28 UTC, sanderland commented on docs/source/cognite.rst
> +.. automethod:: cognite.experimental._api.templates.TemplateGroupVersionsAPI.graphql_query
AttributeError: graphql_query

2021-02-04 08:29 UTC, sanderland requested changes
docs fix please, make html fails.

2021-02-04 09:01 UTC, sanderland approved these changes

2021-02-04 09:12 UTC, merged