Expand functions schedules list filter
cognitedata/cognite-sdk-python-experimental pull request #156
Opened 2021-02-27 12:52 UTC by haakonvt

2021-02-27 14:32 UTC, andeplane commented on cognite/experimental/_api/functions.py
> +            # TODO: The API does not return a nice error message yet
Is there a jira ticket for this now?

2021-03-01 09:36 UTC, haakonvt commented on cognite/experimental/_api/functions.py
> +            # TODO: The API does not return a nice error message yet
```
# Functions list:
CogniteAPIError: {'filter': {'createdTime': {'_schema': ['Invalid input type.']}}} | code: 400 | X-Request-ID: 1827b794-3e2c-95d3-8489-3f5443125ff1

# Compare with i.e. assets list:
CogniteAPIError: Invalid field - filter.createdtime - expected an object but got number | code: 400 | X-Request-ID: bcba77be-e894-909d-8224-8f4856b9952a
```

2021-03-02 11:43 UTC, HMEiding requested changes
Nice! I have a couple of comments. Will you also test these before merging (unfortunately we don't have integration tests...)

2021-03-02 11:43 UTC, HMEiding commented on CHANGELOG.md
> +- The `FunctionsAPI.list()`-method now accepts additional filters: `name`, `owner`, `file_id`, `external_id_prefix` and `created_time`.
There is also a `status` field (although it previously didn't show in the [docs](https://docs.cognite.com/api/playground/#operation/listFunctions)...)

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            # TODO: The API does not return a nice error message yet
The error from the API is from the Marshmallow validation and is the same across all endpoints in context-api. Perhaps the base SDK needs to be updated to handle these appropriately?

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        file_id: int = None,
There is also a `status` field.

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        res = self._post(url_path=f"{self._RESOURCE_PATH}/list", json={"filter": filter, "limit": limit})
The base SDK has a method `_list()`. Any reason for not using that?

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        res = self._post(url_path=f"{self._RESOURCE_PATH}/list", json={"filter": filter, "limit": limit})
The base SDK has a method `_list()`. Any reason for not using that?

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
>          if limit in [float("inf"), -1, None]:
This special handling was necessary when using the endpoint GET `/functions/schedules`. I don't believe it's necessary when calling POST `functions/schedules/list` (but please test to be sure).

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +        return self._cognite_client.functions.schedules.list(function_external_id=self.external_id, limit=limit)
Nice, this is better. 😃

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +    def _load(cls, resource: Union[Dict, str], cognite_client=None):
Is this used anywhere?

2021-03-02 11:43 UTC, HMEiding commented on cognite/experimental/data_classes/functions.py
> +    def _load(cls, resource: Union[Dict, str], cognite_client=None):
Is this used anywhere?

2021-03-02 11:43 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +    url = FUNCTIONS_API._get_base_url_with_base_path() + "/functions/list"
This now mocks the **_filter_** functions endpoint of the API (even though it has url `functions/list` - I know it's confusing), so update the name of the mock accordingly?

2021-03-02 11:43 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +def mock_function_schedules_list_response(rsps):
Update name to `mock_filter_function_schedules_response`

2021-03-02 12:50 UTC, haakonvt commented on CHANGELOG.md
> +- The `FunctionsAPI.list()`-method now accepts additional filters: `name`, `owner`, `file_id`, `external_id_prefix` and `created_time`.
Awesome! This is probably one of the more important fields. I'll add it in!

2021-03-02 12:54 UTC, haakonvt commented on cognite/experimental/_api/functions.py
> +        res = self._post(url_path=f"{self._RESOURCE_PATH}/list", json={"filter": filter, "limit": limit})
Did that first, but it didn't work; the error said something about `cursor` that failed.

2021-03-02 13:28 UTC, haakonvt commented on cognite/experimental/_api/functions.py
>          if limit in [float("inf"), -1, None]:
Passing `limit=None` works as expected, but `limit=math.inf` and `limit=-1` does not work:
```
CogniteAPIError: {'limit': ['Number too large.']} | code: 400 | X-Request-ID: bcbb0eb6-547e-9d01-8ef8-c1c81ed44217

CogniteAPIError: {'limit': ['Must be greater than or equal to 1.']} | code: 400 | X-Request-ID: 174b8f01-ace5-9961-9890-fa899950d6c3
```
Let me know what you want me to do with them; i.e.:
```py
if limit in [float("inf"), -1]:
    limit = None
```

2021-03-02 13:28 UTC, haakonvt commented on cognite/experimental/_api/functions.py
>          if limit in [float("inf"), -1, None]:
(This is probably because we don't use `_list`)

2021-03-02 13:39 UTC, haakonvt commented on cognite/experimental/data_classes/functions.py
> +    def _load(cls, resource: Union[Dict, str], cognite_client=None):
Don't think so; I'll remove!

2021-03-02 13:51 UTC, haakonvt commented on cognite/experimental/_api/functions.py
> +            # TODO: The API does not return a nice error message yet
I've removed my type checks for now, as I guess "Invalid input type" should be sufficient.

2021-03-02 13:53 UTC, haakonvt commented on tests/tests_unit/test_api/test_functions.py
> +    url = FUNCTIONS_API._get_base_url_with_base_path() + "/functions/list"
Aha, a bit confusing yes 😅 Is `mock_functions_filter_response` the correct name?

2021-03-02 14:20 UTC, haakonvt commented
> Nice! I have a couple of comments. Will you also test these before merging (unfortunately we don't have integration tests...)

All the new filter arguments work as expected for both `functions/list` and `schedules/list`. Also tried a few combinations (like `created_time` AND `status`). A few open questions left in this PR for you @HMEiding when you have the time 🚀

2021-03-02 23:43 UTC, HMEiding approved these changes
LGTM 💯  Thanks for contributing!

2021-03-02 23:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        res = self._post(url_path=f"{self._RESOURCE_PATH}/list", json={"filter": filter, "limit": limit})
Ah, you're right. We didn't implement cursors for `functions/list` and `schedules/list` since they are limited to be small in number (but we did for `calls/list`, which can be arbitrarily large). So I guess your `_post()` is fine.

2021-03-02 23:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        if limit in [float("inf"), -1]:
I think you're right about your comment on `_list()` vs `_post()` here; we don't do this special handling for `calls/list`, but that's because we're using `_list()` there.

2021-03-02 23:43 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +    url = FUNCTIONS_API._get_base_url_with_base_path() + "/functions/list"
I think that's fine. 😄

2021-03-03 09:06 UTC, merged