Native tokens direct function call and create function schedule
cognitedata/cognite-sdk-python-experimental pull request #162
Opened 2021-03-23 14:44 UTC by qTipTip

2021-04-30 13:43 UTC, HMEiding requested changes
Nice! I have a few comments/questions.

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +import requests
This is not used.

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            client_credentials (dict, optional): Optional client credentials with "client_secret", "client_id", and "scope". These will override
This was not part of the doc we agreed on, right?

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        and client_config.token_scopes
See comment above.

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        scopes = cognite_client.config.token_scopes
I think the scope is no longer part of the session create request (ref. post in #oidc-tokens on April 7th).

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +                scopes
See comment above.

2021-04-30 13:43 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        client_credentials: Dict = None,
I guess this should be optional - the user might want to schedule a "Hello, World"-type function.

2021-04-30 13:44 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            client_credentials (dict, optional): Optional client credentials with "client_secret", "client_id", and "scope". These will override
Ah / I misunderstood then. 

So, if you're using token a token, then we enforce on-behalf of?

2021-04-30 13:49 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +def _use_client_credentials(cognite_client: CogniteClient, client_credentials: Optional[Dict] = None):
Code duplication, mainly. :)

2021-04-30 13:50 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +        scopes = cognite_client.config.token_scopes
Okay, will look into it!

2021-04-30 13:59 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        client_credentials: Dict = None,
Set this as optional?

2021-04-30 14:06 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        # Case 1: Client credentials, either passed in explicitly, or inferred from the instantiated client.
Update comment.

2021-04-30 14:06 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            client_credentials (dict, optional): Optional client credentials with "client_secret", "client_id", and "scope". These will override
Is perhaps the cleanest?

2021-04-30 14:10 UTC, HMEiding requested changes
Just a couple of smaller comments. 🙂 Remember to update CHANGELOG.md and tests.

2021-04-30 14:10 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        client_credentials: Dict = None,
Set this optional.

2021-04-30 14:10 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        # Case 1: Client credentials, either passed in explicitly, or inferred from the instantiated client.
Update comment.

2021-04-30 14:10 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +f
Oopsie?

2021-04-30 14:12 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +f
Oopsie

2021-05-20 11:43 UTC, HMEiding requested changes
Very nice! Just a couple of comments and questions.

2021-05-20 11:43 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +        base_url=COGNITE_CLIENT.config.base_url,
Just out of curiosity, do you need to set `base_url` and `project`? They were not set [here](https://github.com/cognitedata/cognite-sdk-python-experimental/pull/162/files#diff-7398b18750acb9ae1cc47a240df731afa0574adc92fe71c2bb0a8e401e401126R19).

2021-05-20 11:43 UTC, HMEiding commented on tests/tests_unit/test_api/test_functions.py
> +def mock_functions_call_response_oidc(mock_functions_call_responses):
I think this could in fact be taylor made to each of the two uses cases we have by matching on the request-body. See [here](https://github.com/getsentry/responses#matching-request-parameters). Then we test that the correct request is actually being made. What do you think?

2021-05-20 11:45 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +def mock_functions_call_response_oidc(mock_functions_call_responses):
Good idea! I thought of the same thing, but I decided to not do it, as I found no immediate way of doing it. But yes, actually verifying the correct post-bodies are made is a good idea. I'll take a look!

2021-05-20 11:45 UTC, qTipTip commented on tests/tests_unit/test_api/test_functions.py
> +        base_url=COGNITE_CLIENT.config.base_url,
Maybe not! Will verify.

2021-05-20 11:46 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +
Yes :D

2021-05-20 11:49 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +        and client_config.token_url
I think `client_secret` and `client_id` does not make sense to talk about on their own. We also need to know which entity issued it, which is encoded in the `token_url` as far as I know, and the scopes I am not sure of .

I followed https://cognite-docs.readthedocs-hosted.com/projects/cognite-sdk-python/en/latest/cognite.html#cogniteclient

2021-05-21 12:19 UTC, HMEiding reviewed
Should we try to figure out the roles of `token_url` and `token_scopes`? Ref. my question below.

2021-05-21 12:19 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        and client_config.token_url
But the `client_id` and `client_secret` are used alone [here](https://github.com/cognitedata/cognite-sdk-python-experimental/pull/162/files#diff-e2d4cc4b362176e67c21d15c5a26408ebbf887c2848013d5f75fd30905857fb9R414), no?

2021-05-25 10:29 UTC, HMEiding approved these changes
Very nice! 😄 See my comments though. Also remember to bump the version in pyproject.toml.

2021-05-25 10:29 UTC, HMEiding commented on CHANGELOG.md
> +- `FunctionsAPI.call` now uses OICD tokens if the client was instantiated with a token or client credentials.
```suggestion
- `FunctionsAPI.call` now uses OIDC tokens if the client was instantiated with a token or client credentials.
```

2021-05-25 10:29 UTC, HMEiding commented on CHANGELOG.md
> +- `FunctionSchedulesAPI.create` now supports OICD tokens through the use of client-credentials, explicitly passed in as an argument.
```suggestion
- `FunctionSchedulesAPI.create` now supports OIDC tokens through the use of client-credentials, explicitly passed in as an argument.
```

2021-05-25 10:29 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        # Exchanging the token for a nonce.
Nitpick, but this is only the case for scenario 2.

2021-05-25 10:29 UTC, HMEiding commented on CHANGELOG.md
>  ## [0.52.0]
Should be 0.53.0

2021-05-25 11:32 UTC, merged