[MLOPS-965] Add optional argument runtime to FunctionsAPI.create()
cognitedata/cognite-sdk-python-experimental pull request #266
Opened 2022-01-26 12:44 UTC by HMEiding

2022-02-01 11:09 UTC, qTipTip requested changes

2022-02-01 11:09 UTC, qTipTip commented on cognite/experimental/_api/functions.py
> +            runtime (str, optional):                The function runtime. Valid values are ["py37", "py38", "py39", `None`], and `None` translates to the API default.
What about `js`?

2022-02-02 09:02 UTC, qTipTip approved these changes
LGTM!

2022-02-02 17:59 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +            runtime (str, optional):                The function runtime. Valid values are ["py37", "py38", "py39", `None`], and `None` translates to the API default.
As agreed, we leave `js` undocumented as long as it is not officially supported.

2022-02-03 07:26 UTC, merged