Add support to specify metadata when creating a function
cognitedata/cognite-sdk-python-experimental pull request #288
Opened 2022-02-22 09:55 UTC by anothercoginthewheel

* Add optional argument metadata to FunctionsAPI.create()

* Update pyproject.toml

2022-02-22 12:19 UTC, HMEiding requested changes
Great! 💯 Only some small suggestions.

2022-02-22 12:19 UTC, HMEiding commented on CHANGELOG.md
> +## [0.68.4]
Should this be a bump in minor version? Ref [here](https://semver.org/#:~:text=PATCH%2C%20increment%20the%3A,make%20backwards%20compatible%20bug%20fixes.).

2022-02-22 12:19 UTC, HMEiding commented on CHANGELOG.md
> +- Optional argument `metadata` to `FunctionsAPI.create` which allows metadata in the form of key:value pairs to be added to each function.
```suggestion
- Optional argument `metadata` to `FunctionsAPI.create` which allows metadata in the form of key:value pairs of strings to be added to each function.
```

2022-02-22 12:19 UTC, HMEiding commented on cognite/experimental/_api/functions.py
> +        if metadata:
Since you have `allow_none=True` in your context-api PR ([here](https://github.com/cognitedata/context-api/pull/2604/files#diff-fafc9e8379c9d5c7fb7b072dae17eea9f48f7579a2d17707003cb82b4cbbd172R128)), you actually don't need the if-test: You can just add the metadata to the body. The if-test is only needed for those properties that have `allow_none=False`.

2022-02-22 12:19 UTC, HMEiding commented on pyproject.toml
> +version = "0.68.4"
Bump minfor version?

2022-02-23 09:45 UTC, anothercoginthewheel commented on cognite/experimental/_api/functions.py
> +        if metadata:
Made this so.

2022-02-23 11:17 UTC, HMEiding approved these changes
LGTM 👍

2022-02-24 08:02 UTC, merged