[CDF-8458], Add update models
cognitedata/cognite-sdk-python-experimental pull request #86
Opened 2020-08-19 11:53 UTC by rebwib

This solves https://cognitedata.atlassian.net/browse/CDF-8458?atlOrigin=eyJpIjoiYzFmNjA0ZjYyYmU2NDAxYWFjMjM4NGZlMmRkODdmZjAiLCJwIjoiaiJ9

@sanderland I was not sure what to return. Hope you can give me feedback on whether we should return a list or a model objevt.

2020-08-19 11:53 UTC, sanderland commented on cognite/experimental/_context_client.py
> +    def retrieve(self, model_id: int) -> Union[EntityMatchingModel]:
union with what?

2020-08-19 11:59 UTC, sanderland requested changes
the update call itself should return a list of updated objects, so you should not need to have to call retrieve either before or after. this should only be a single http call.

the sdk takes List[Union[Asset, AssetUpdate]] which is quite involved with autogeneration magic etc.
I would suggest taking a list of models and just throw the entire model dumps at the update endpoint, and have the update endpoint complain if some fields are set that both change and aren't updateable.   is there something in the api design for this?

2020-08-19 12:14 UTC, rebwib commented on cognite/experimental/_context_client.py
> +    def retrieve(self, model_id: int) -> Union[EntityMatchingModel]:
After we removed resource typing it is alway  `EntityMatchingModel` so I can remove the union.

2020-08-19 12:34 UTC, rebwib commented
> the update call itself should return a list of updated objects, so you should not need to have to call retrieve either before or after. this should only be a single http call.
> 
> the sdk takes List[Union[Asset, AssetUpdate]] which is quite involved with autogeneration magic etc.
> I would suggest taking a list of models and just throw the entire model dumps at the update endpoint, and have the update endpoint complain if some fields are set that both change and aren't updateable. is there something in the api design for this?

I tried to follow how the SDK updates for instance an asset when i created this method. However, was a bit unsure about the response. Changed it in my last commit. As of now, it is only possible to update one model with each update-call. The reason was to resemble update in the SDK.

There is a section on update in the API design, https://github.com/cognitedata/service-contracts/blob/master/design_guide/API_design_guide.md#update I tried to follow that when I created the update endpoint.

2020-08-19 12:39 UTC, sanderland commented on cognite/experimental/_context_client.py
> +        return self._camel_post("/update", json={"items": [{"modelId": model.model_id, "update": update_dict}]}).json()
definitely convert this to an EntityMatchingModel again though :)

2020-08-19 12:40 UTC, sanderland commented
> > the update call itself should return a list of updated objects, so you should not need to have to call retrieve either before or after. this should only be a single http call.
> > the sdk takes List[Union[Asset, AssetUpdate]] which is quite involved with autogeneration magic etc.
> > I would suggest taking a list of models and just throw the entire model dumps at the update endpoint, and have the update endpoint complain if some fields are set that both change and aren't updateable. is there something in the api design for this?
> 
> I tried to follow how the SDK updates for instance an asset when i created this method. However, was a bit unsure about the response. Changed it in my last commit. As of now, it is only possible to update one model with each update-call. The reason was to resemble update in the SDK.
> 
> There is a section on update in the API design, https://github.com/cognitedata/service-contracts/blob/master/design_guide/API_design_guide.md#update I tried to follow that when I created the update endpoint.

Don't really like the retrieve call, but alright then, efficiency shouldn't be that important here.

2020-08-19 13:13 UTC, rebwib commented on cognite/experimental/_context_client.py
> +        return self._camel_post("/update", json={"items": [{"modelId": model.model_id, "update": update_dict}]}).json()
See 5d8f473. If that was not correct, it would be great if you could push a fix to this branch.

2020-08-19 13:14 UTC, rebwib commented
> > > the update call itself should return a list of updated objects, so you should not need to have to call retrieve either before or after. this should only be a single http call.
> > > the sdk takes List[Union[Asset, AssetUpdate]] which is quite involved with autogeneration magic etc.
> > > I would suggest taking a list of models and just throw the entire model dumps at the update endpoint, and have the update endpoint complain if some fields are set that both change and aren't updateable. is there something in the api design for this?
> > 
> > 
> > I tried to follow how the SDK updates for instance an asset when i created this method. However, was a bit unsure about the response. Changed it in my last commit. As of now, it is only possible to update one model with each update-call. The reason was to resemble update in the SDK.
> > There is a section on update in the API design, https://github.com/cognitedata/service-contracts/blob/master/design_guide/API_design_guide.md#update I tried to follow that when I created the update endpoint.
> 
> Don't really like the retrieve call, but alright then, efficiency shouldn't be that important here.

I didn't really like it either, but wasn't sure how else to do it.

2020-08-19 13:34 UTC, sanderland commented
in the sdk it's
```
    def _get_update_properties(cls):
        return [key for key in cls.__dict__.keys() if (not key.startswith("_")) and (not key == "labels")]
```
i.e. everything is updateable and the backend ignores things like id if they're the same

2020-08-19 13:39 UTC, rebwib commented
> ef _get_update_properties(cls):
>         return [key for key in cls.__dict__.keys() if (not key.startswith("_")) and (not key == "labels")]

Then we have to change the api as well, since for now it only lets you update name and description. Should we let the user update e.g. feature_type?

2020-08-20 11:56 UTC, sanderland approved these changes

2020-08-20 11:56 UTC, merged